### ISSUE TITLE
Running into an error with npm install

### ISSUE THREAD

**Issue by alecnicolas** [oktadeveloper/schematics#192]
Using [https://developer.okta.com/blog/2019/05/13/angular-8-spring-boot-2](url) to set up Okta on an Angular and Spring app.

Upon running `ng add @oktadev/schematics`:

`ENOENT: no such file or directory, open './package-lock.json'`

**Comment by frlzjosh** [comment]
I get the same issue when doing `ng add @oktadev/schematics` as well as with yarn. The error is always ends up being:  
```
npx npm-force-resolutions
Arguments:
Directory: /Users/disjosh/Documents/SCHOOL/COMP586/carFinder/car-app/node_modules/@oktadev/schematics
Output:
```

**Comment by mraible** [comment]
If you run "npm install" first, does it work?

**Comment by mraible** [comment]
Thanks for reporting this issue. Fixing now...

**Comment by mraible** [comment]
Should be fixed now.

**Comment by bertyhell** [comment]
For future reference this was fixed by removing the npx npm-force-resolutions command from package json:
https://github.com/oktadeveloper/schematics/commit/1d228f380f291a3f274551dc8a07e76340854e98
