### ISSUE TITLE
Signup Redirection Issue

### ISSUE THREAD

**Issue by zlannin** [oktadeveloper/schematics#223]
Users who signup for our app but verify their email from a different device like desktop web. It appears the verify email button is trying to use the app callback url `com.okta.dev-123456:/callback?iss=<oauth url>&login_hint=EMAIL_VERIFICATION&session_hint=AUTHENTICATED&login_hint=<registered users email>`. This is causing users to see a 404 page when clicking Verify Email.

**Comment by mraible** [comment]
What type of application are you experiencing this issue with? Is it Ionic or React Native? 

Either way, I don't think this is an issue that's related to this library.

**Comment by zlannin** [comment]
Ionic Capacitor. I'm asking here as well because I wasn't sure if there was a setting I could change.

**Comment by mraible** [comment]
It's not a setting you can change in your code (or the code this library generates) as far as I know. I'd suggest asking about it on our <a href="https://devforum.okta.com/">Developer Forums</a>.
