### ISSUE TITLE
Unable to get refresh token when adding 'offline_access'

### ISSUE THREAD

**Issue by Haharis** [oktadeveloper/schematics#423]
Hi,

Following your guide https://developer.okta.com/blog/2019/06/20/ionic-4-tutorial-user-authentication-and-registration which is great, I noticed that when I add the 'offline_access' scope (to get the refresh token) in the configuration, the /token gets an error saying that this scope is not supported.

In fact, while implementing Authorization Code flow, you need to specify 'offline_access'' on the /authorize endpoint instead of /token (https://developer.okta.com/docs/guides/refresh-tokens/get-refresh-token/)

My question is : is it possible to specify the offline_access only for the /authorize endpoint instead of both with OktaDev Schematics ?

Thanks in advance,
Bruno.

**Comment by mraible** [comment]
Do you get this error in your browser or when running on an emulator (or
device)? In my experience, refresh tokens won't (and shouldn't) work in a
browser. They should only work when you're running from the device.
