### ISSUE TITLE
Unable To Obtain Server Configuration in ios simulator

### ISSUE THREAD

**Issue by kuttimania** [oktadeveloper/schematics#445]
Having issue in ios simulator while using "ionic-native-http-connection-backend"

Package:
  "@angular/cli": "~10.0.5",
   "@oktadev/schematics": "^3.0.0",
    "ionic-native-http-connection-backend": "^8.0.0" (without out this package its working )

**Comment by mraible** [comment]
Are you saying that everything works until you add this new dependency? If
so, why are you adding this dependency?

**Comment by kuttimania** [comment]
This plugin we used for overcome CORS issues server side

**Comment by mraible** [comment]
I'm confused. Returning CORS headers on the server doesn't have anything to
do with the client in my experience. OktaDev Schematics uses the Cordova
Native HTTP plugin to override the "capacitor://localhost" origin header
that Capacitor sends.

https://ionicframework.com/docs/native/http
