### ISSUE TITLE
Issue in getting new access token

### ISSUE THREAD

**Issue by dhaivat28Ezypay** [oktadeveloper/schematics#457]
Hi, I have create a new ionic app with angular using the okta-dev/schematics and i am facing an issue where the user gets logged out automatically as the token expires and call to /token endpoint fails with the following error.

![Screen Shot 2020-11-16 at 5 35 17 pm](https://user-images.githubusercontent.com/61716512/99751399-3ad1fa00-2b36-11eb-8f92-d50eff55be3a.png)

I have allowded the grant type refresh token in my application created in okta. But what i have found is that the getValidToken() is causing this issue if the token in the local storage has expired. It tries to make  a call to /token endpoint for a refreshToken with grant_type as refresh_token and thus it returns with the above error and gets the user logged out.

`package.json

{
  "name": "test",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "dev": "ionic serve",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "generate-types": "graphql-codegen --config codegen.yml"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@capacitor/android": "^2.4.1",
    "@capacitor/core": "^2.4.1",
    "@capacitor/ios": "^2.4.1",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/http": "5.27.0",
    "@ionic-native/secure-storage": "5.23.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.3.3",
    "@oktadev/schematics": "^2.2.0",
    "apollo-angular": "^2.0.4",
    "cordova-plugin-advanced-http": "3.0.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-safariviewcontroller": "1.6.0",
    "cordova-plugin-secure-storage-echo": "5.1.1",
    "ionic-appauth": "0.5.1",
    "jetifier": "^1.6.6",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3",
    "@apollo/client": "^3.0.0",
    "graphql": "^15.0.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/cli": "~10.0.5",
    "@angular/compiler": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@angular/language-service": "~10.0.0",
    "@capacitor/cli": "2.4.1",
    "@graphql-codegen/cli": "1.17.10",
    "@ionic/angular-toolkit": "^2.3.3",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5",
    "@graphql-codegen/typescript-apollo-angular": "2.0.1",
    "@graphql-codegen/typescript": "1.17.10",
    "@graphql-codegen/typescript-operations": "1.17.8",
    "@graphql-codegen/introspection": "1.18.0"
  },
}`

Thanks in Advance

**Comment by mraible** [comment]
Yeah, refresh tokens won't work in a browser-based app with Okta. They'll
work just fine when packaged and run as a mobile app. We might have a
solution in the next few months.

**Comment by dhaivat28Ezypay** [comment]
Thanks @mraible for the response. Is there any temporary fix that you can suggest untill its being supported by okta as we are stuck now and the app logout user every hour?

**Comment by mraible** [comment]
The only solution I know of is to set a long TTL on your access token. Our
SDKs have a workaround, but Ionic is using Ionic AppAuth, which we do not
maintain.

Just curious, are you planning to deploy this to a mobile device? If so,
will you be using Cordova or Capacitor?

**Comment by dhaivat28Ezypay** [comment]
okays got it. We we are planning to deploy it on all three platforms using capacitor.

**Comment by mraible** [comment]
We might have a better workaround in the near future for refresh tokens in the browser. I'm not sure when it'll be released though.

**Comment by dhaivat28Ezypay** [comment]
Yes we really hope. Thanks
